#!/bin/sh
# Create the Mnemify desktop launcher.
#
#   sh scripts/make-launcher.sh [REPO_ROOT]
#
# macOS  -> ${MNEMIFY_LAUNCHER_DIR:-$HOME/Applications}/Mnemify.app
# Linux  -> ${MNEMIFY_LAUNCHER_DIR:-$HOME/.local/share/applications}/mnemify.desktop
#
# The launcher hardcodes the absolute path of this checkout. If you move or
# rename the folder, re-run `sh setup.sh` from the new location to rewrite it.
#
# Safe to run repeatedly: it overwrites what is already there.
#
# POSIX sh — tested with dash and bash. No bashisms.

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
REPO=${1:-$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd -P)}
REPO=$(CDPATH='' cd -- "$REPO" && pwd -P)

if [ ! -f "$REPO/mnemify.sh" ]; then
    printf 'make-launcher: %s does not look like a Mnemify checkout.\n' "$REPO" >&2
    exit 1
fi

VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' "$REPO/backend/pyproject.toml" 2>/dev/null | head -1)
[ -n "$VERSION" ] || VERSION="1.0.0"

case "$(uname -s)" in
Darwin)
    APP_DIR=${MNEMIFY_LAUNCHER_DIR:-$HOME/Applications}
    APP="$APP_DIR/Mnemify.app"
    mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

    # LSUIElement = true: the launcher is a shell stub that lives for as long as
    # the server does. As a normal app it would sit in the Dock forever with no
    # windows of its own (the UI is a browser tab), and Cmd-Q on that tile would
    # hard-kill the server behind the user's back. LSUIElement still allows the
    # osascript failure dialog — LSBackgroundOnly would not, and that dialog is
    # the only way a GUI launch can report "run setup.sh first".
    cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Mnemify</string>
	<key>CFBundleExecutable</key>
	<string>Mnemify</string>
	<key>CFBundleIconFile</key>
	<string>Mnemify</string>
	<key>CFBundleIdentifier</key>
	<string>ai.mnemify.app</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Mnemify</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$VERSION</string>
	<key>CFBundleVersion</key>
	<string>$VERSION</string>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
PLIST

    # Write the stub to a temp file and move it into place: replacing the
    # executable of a currently-running app in place can fail with ETXTBSY.
    STUB_TMP="$APP/Contents/MacOS/.Mnemify.new"
    cat > "$STUB_TMP" <<STUB
#!/bin/bash
# Generated by scripts/make-launcher.sh — re-run \`sh setup.sh\` if you move the folder.
exec /bin/bash "$REPO/mnemify.sh" --gui
STUB
    chmod 755 "$STUB_TMP"
    mv -f "$STUB_TMP" "$APP/Contents/MacOS/Mnemify"

    if [ -f "$REPO/assets/icons/mnemify.icns" ]; then
        cp -f "$REPO/assets/icons/mnemify.icns" "$APP/Contents/Resources/Mnemify.icns"
    fi

    # Nudge Finder/Launchpad into re-reading the bundle so the icon refreshes.
    touch "$APP" 2>/dev/null || true
    if command -v plutil >/dev/null 2>&1; then
        plutil -lint "$APP/Contents/Info.plist" >/dev/null 2>&1 || \
            printf 'make-launcher: warning — Info.plist did not pass plutil -lint\n' >&2
    fi

    printf 'Launcher: %s\n' "$APP"
    printf 'Find it in Launchpad, or in Finder under Go -> Applications (it is in your personal %s).\n' "$APP_DIR"
    ;;
Linux|*)
    APP_DIR=${MNEMIFY_LAUNCHER_DIR:-$HOME/.local/share/applications}
    DESKTOP="$APP_DIR/mnemify.desktop"
    mkdir -p "$APP_DIR"
    cat > "$DESKTOP" <<DESK
[Desktop Entry]
Type=Application
Version=1.0
Name=Mnemify
GenericName=Knowledge map
Comment=Your knowledge, as a world you can explore
Exec=/bin/bash "$REPO/mnemify.sh" --gui
Icon=$REPO/assets/icons/mnemify-1024.png
Path=$REPO
Terminal=false
# false on purpose: the stub never opens a window of its own (the UI is a
# browser tab), so a startup notification would just spin until it times out.
StartupNotify=false
Categories=Office;Utility;
X-Mnemify-Version=$VERSION
DESK
    chmod 644 "$DESKTOP"
    if command -v update-desktop-database >/dev/null 2>&1; then
        update-desktop-database "$APP_DIR" >/dev/null 2>&1 || true
    fi
    printf 'Launcher: %s\n' "$DESKTOP"
    printf 'Find it in your application menu as "Mnemify" (you may need to log out and back in once).\n'
    ;;
esac
